/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nganhang;

import DBCN.ConectDB;
import java.sql.Connection;
import javax.swing.JOptionPane;
import DBCN.ConectDB;
import java.lang.String;
import DBCN.DB_hskh;
import DBCN.DB_stk;
import DBCN.DB_hdvay;
import javax.swing.table.DefaultTableModel;
import nganhang.hosokhachhang;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.util.Date;

public class frmHoso extends javax.swing.JFrame {

    /**
     * Creates new form frmHoso
     */
    public frmHoso() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Hệ thống quản lý Ngân hàng HNC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stg = new javax.swing.JTextField();
        ls = new javax.swing.JTextField();
        sng = new javax.swing.JTextField();
        stl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        stv = new javax.swing.JTextField();
        mls = new javax.swing.JTextField();
        httt = new javax.swing.JTextField();
        sTv = new javax.swing.JTextField();
        nv = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nt = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnSửa = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtmtk = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtLai = new javax.swing.JTextField();
        txtGoc = new javax.swing.JTextField();
        btnRutlai = new javax.swing.JButton();
        btnRutgoc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        txtVay = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTra = new javax.swing.JTextField();
        btnTra = new javax.swing.JButton();
        btnLichsu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Danh sách hồ sơ khách hàng");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Quay lại trang chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Ngân hàng HNC");

        btnTimkiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nhập mã hồ sơ");

        txtNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hồ sơ", "Loại hồ sơ", "Họ tên người mở", "Số điện thoại", "Địa chỉ", "Hạn mức tín dụng", "Ngày tạo", "Tên tổ chức"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã số vay", "Tiền vay(triệu)", "Mức lãi suất", "Ngày vay", "Số tháng vay", "HT thanh toán"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã STK", "Tiền gốc(triệu) ", "Lãi suất (%)", "Tiền lãi (triệu)", "Ngày tạo", "Số năm gửi"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Hợp đồng vay vốn");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Sổ tiết kiệm");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Số tiền gốc");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Lãi suất");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Số tiền lãi");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Số năm gửi");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Ngày tạo");

        stg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stgActionPerformed(evt);
            }
        });

        ls.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsActionPerformed(evt);
            }
        });

        sng.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sngActionPerformed(evt);
            }
        });

        stl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stlActionPerformed(evt);
            }
        });

        jLabel11.setText("(VND)");

        jLabel12.setText("(VND)");

        jLabel13.setText("(%)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Số tiền vay");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Mức lãi suất");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Số tháng vay");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("HT thanh toán");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Ngày vay");

        stv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stvActionPerformed(evt);
            }
        });

        mls.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlsActionPerformed(evt);
            }
        });

        httt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        httt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htttActionPerformed(evt);
            }
        });

        sTv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTvActionPerformed(evt);
            }
        });

        jLabel19.setText("(VND)");

        jLabel20.setText("(%)");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Mở sổ ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Tạo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnSửa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSửa.setText("Chỉnh sửa hồ sơ");
        btnSửa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSửaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Mã STK");

        txtmtk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtmtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmtkActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Rút tiền lãi");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Rút tiền gốc");

        txtLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLaiActionPerformed(evt);
            }
        });

        btnRutlai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRutlai.setText("Rút lãi");
        btnRutlai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutlaiActionPerformed(evt);
            }
        });

        btnRutgoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRutgoc.setText("Rút gốc");
        btnRutgoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutgocActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Mã Số vay");

        txtVay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVayActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Trả tiền");

        txtTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraActionPerformed(evt);
            }
        });

        btnTra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTra.setText("Trả");
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });

        btnLichsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLichsu.setText("Lịch sử giao dịch");
        btnLichsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLichsu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSửa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(jLabel4)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ls, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sng, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(159, 159, 159)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(159, 159, 159)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel21)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLai, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRutlai, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRutgoc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtmtk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(390, 390, 390)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stv, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sTv)
                                            .addComponent(httt)
                                            .addComponent(nv, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(mls, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel24)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtVay, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLichsu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSửa))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(mls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel20))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButton4)
                                                .addComponent(jButton2)))))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sTv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(httt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(stl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sng, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmtk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRutlai))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRutgoc)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(txtTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTra)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:

        int xet = 0;

        Object obj[] = new Object[8];
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel model3 = (DefaultTableModel) jTable3.getModel();
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();

        model.setRowCount(0);
        model2.setRowCount(0);
        model3.setRowCount(0);

        String a = txtNhap.getText();
        if (a.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập mã hồ sơ!!!");
        } else {
            DB_hskh tkk = new DB_hskh();

            for (hosokhachhang i : tkk.layhoso()) {

                if (i.getMaHS().equals(a)) {

                    obj[0] = i.getMaHS();
                    obj[1] = i.getLoaiHS();
                    obj[2] = i.getTenDK();
                    obj[3] = i.getSdt();
                    obj[4] = i.getDiachi();
                    obj[5] = i.getHanmuc();
                    obj[6] = i.getNgaytaoHS();
                    obj[7] = i.getTentochuc();

                    model.addRow(obj);

                    DB_stk s1 = new DB_stk();
                    Object obj1[] = new Object[6];

                    for (Sotietkiem j : s1.laystk()) {
                        if (j.getChuhoso().equals(a)) {
                            obj1[0] = j.getMaSTK();
                            double m = j.getSotiengoc();
                            m = m / 1000000;
                            obj1[1] = m;
                            obj1[2] = j.getLaisuat();
                            double n = j.getSotienlai();
                            n = n / 1000000;
                            obj1[3] = n;
                            obj1[4] = j.getNgaygui();
                            obj1[5] = j.getThoihangui();

                            model3.addRow(obj1);
                        }
                    }

                    DB_hdvay s2 = new DB_hdvay();
                    Object obj2[] = new Object[6];

                    for (Hopdongvayvon t : s2.layhd()) {
                        if (t.getChuhoso().equals(a)) {
                            obj2[0] = t.getMavay();
                            double p = t.getSotienvay();
                            p = p / 1000000;
                            obj2[1] = p;
                            obj2[2] = t.getMuclaisuat();
                            obj2[3] = t.getNgayvay();
                            obj2[4] = t.getThoihanvay();
                            obj2[5] = t.getHinhthuc();

                            model2.addRow(obj2);
                        }
                    }

                    xet = 1;
                }

            }
            if (xet == 0) {
                JOptionPane.showMessageDialog(rootPane, "Không tồn tại mã khách hàng này!");

            }
        }


    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmHNC().setVisible(true);
            }
        });

        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stgActionPerformed

    private void lsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsActionPerformed

    private void sngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sngActionPerformed

    private void stlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stlActionPerformed

    private void stvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stvActionPerformed

    private void mlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mlsActionPerformed

    private void sTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTvActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String b = txtNhap.getText();
        if (b.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập mã hồ sơ!!!");
        } else {
            if ((stg.getText().equals("")) || (ls.getText().equals("")) || (stl.getText().equals(""))
                    || (sng.getText().equals(""))) {
                JOptionPane.showMessageDialog(rootPane, "Nhập thiếu thông tin!!!");
            } else {
                try {
                    Connection cn = ConectDB.getConectDB();
                    PreparedStatement ps = cn.prepareStatement("Insert into Sotietkiem (Sotiengoc, Laisuat , Sotienlai, Ngaytao, Thoihan, Chuhoso) Values (?,?,?,?,?,?)");
                    double k1 = Double.parseDouble(stg.getText());
                    ps.setDouble(1, k1);

                    double k2 = Double.parseDouble(ls.getText());
                    ps.setDouble(2, k2);

                    double k3 = Double.parseDouble(stl.getText());
                    ps.setDouble(3, k3);

                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String d = sdf.format(nt.getDate());
                    ps.setString(4, d);

                    int k4 = Integer.parseInt(sng.getText());
                    ps.setInt(5, k4);

                    ps.setString(6, b);

                    int check = ps.executeUpdate();

                    JOptionPane.showMessageDialog(rootPane, "Đã mở thành công sổ tiết kiệm!");
                    stg.setText("");
                    ls.setText("");
                    stl.setText("");
                    sng.setText("");

                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(taocanhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void htttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_htttActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String c = txtNhap.getText();
        DB_hskh hskh = new DB_hskh();

        if (c.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập mã hồ sơ!!!");
        } else {
            long hanmuc1 = 0;
            for (hosokhachhang d : hskh.layhoso()) {
                if (d.getMaHS().equals(c)) {
                    hanmuc1 = d.getHanmuc();
                }
            }
            double hanmuc2 = hanmuc1;

            if ((stv.getText().equals("")) || (mls.getText().equals("")) || (sTv.getText().equals(""))
                    || (httt.getText().equals(""))) {
                JOptionPane.showMessageDialog(rootPane, "Nhập thiếu thông tin!!!");
            } else {
                {
                    double l1 = Double.parseDouble(stv.getText());
                    DB_hdvay hdv1 = new DB_hdvay();
                    double tong1;
                    tong1 = l1;
                    for (Hopdongvayvon g : hdv1.layhd()) {
                        if (g.getChuhoso().equals(c)) {
                            tong1 = tong1 + g.getSotienvay();
                        }
                    }

                    if (tong1 > hanmuc2) {
                        JOptionPane.showMessageDialog(rootPane, "Vượt quá hạn mức tín dụng!!!");
                    } else {

                        try {
                            Connection cn = ConectDB.getConectDB();
                            PreparedStatement ps = cn.prepareStatement("Insert into Hopdongvayvon (Sotienvay, Muclaisuat , Ngayvay, Thoihan, Hinhthucthanhtoan, Chuhoso) Values (?,?,?,?,?,?)");
                            double h1 = Double.parseDouble(stv.getText());
                            ps.setDouble(1, h1);

                            double h2 = Double.parseDouble(mls.getText());
                            ps.setDouble(2, h2);

                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String d = sdf.format(nv.getDate());
                            ps.setString(3, d);

                            int h4 = Integer.parseInt(sTv.getText());
                            ps.setInt(4, h4);

                            ps.setString(5, httt.getText());

                            ps.setString(6, c);

                            int check = ps.executeUpdate();

                            JOptionPane.showMessageDialog(rootPane, "Đã tạo thành công hồ sơ vay vốn!");
                            stv.setText("");
                            mls.setText("");
                            sTv.setText("");
                            httt.setText("");

                        } catch (SQLException ex) {
                            java.util.logging.Logger.getLogger(taocanhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        }
                    }
                }

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtmtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmtkActionPerformed

    private void txtLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLaiActionPerformed

    private void txtVayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVayActionPerformed

    private void txtTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraActionPerformed

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        // TODO add your handling code here:
        String o = txtNhap.getText();
        String k = txtVay.getText();
        if (k.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hợp đồng cần trả!!!");
        } else {

            String h = txtTra.getText();
            if (h.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập số tiền muốn trả!!!");
            } else {

                double tien3 = Double.parseDouble(h);

                int ma3 = Integer.parseInt(k);

                DB_hdvay hopdong = new DB_hdvay();

                for (Hopdongvayvon i : hopdong.layhd()) {

                    if (i.getMavay() == ma3) {

                        if (i.getSotienvay() < tien3) {

                            JOptionPane.showMessageDialog(rootPane, "Số tiền trả nhiều hơn số tiền đang nợ!!!");

                        } else {

                            double d3 = i.getSotienvay() - tien3;

                            try {
                                Connection cn = ConectDB.getConectDB();
                                PreparedStatement ps = cn.prepareStatement("update Hopdongvayvon set Sotienvay=? where Msvay=?");

                                ps.setDouble(1, d3);
                                ps.setInt(2, ma3);

                                int check = ps.executeUpdate();
                                
                                Date date = new java.util.Date();
                                SimpleDateFormat sd = new SimpleDateFormat("hh:mm:ss dd-MM-yyyy");
                                String d = sd.format(date);
                                tien3=tien3/1000000;
                                String nd1 = "Trả "+tien3+" triệu VNĐ tiền nợ từ hợp đồng "+ma3;
                                
                                PreparedStatement ps1 = cn.prepareStatement("Insert into Lichsu (Time, Nhanvien, Noidung, Chuhoso) Values (?,?,?,?)");

                                ps1.setString(1, d);
                                ps1.setString(2, taikhoannhanvien.nhanvien);
                                ps1.setString(3, nd1);
                                ps1.setString(4, o);
                                
                                int check1 = ps1.executeUpdate();

                                JOptionPane.showMessageDialog(rootPane, "Đã trả thành công!");

                            } catch (SQLException ex) {
                                java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnTraActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int row = jTable3.getSelectedRow();
        int a = ((int) (jTable3.getValueAt(row, 0)));
        String t = String.valueOf(a);
        txtmtk.setText(t);

    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        int a = ((int) (jTable2.getValueAt(row, 0)));
        String t = String.valueOf(a);
        txtVay.setText(t);
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnSửaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSửaActionPerformed
        // TODO add your handling code here:
        String a = txtNhap.getText();

        if (a.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập mã hồ sơ!!!");
        } else {
            int row = jTable1.getSelectedRow();
            String b1 = ((String) jTable1.getValueAt(row, 2));
            String b2 = ((String) jTable1.getValueAt(row, 3));
            String b3 = ((String) jTable1.getValueAt(row, 4));
            String b4 = String.valueOf(jTable1.getValueAt(row, 5));
            String b5 = ((String) jTable1.getValueAt(row, 7));
            System.out.println(b4);

            try {
                Connection cn = ConectDB.getConectDB();
                PreparedStatement ps = cn.prepareStatement("UPDATE Hoso SET Tendk=?, Sdt=?, Diachi=?, Hmtd=?, TenTC=?  where MaHs=?");
                ps.setString(1, b1);
                ps.setString(2, b2);
                ps.setString(3, b3);
                long bb = 0; 
                bb = Long.parseLong(b4);
                ps.setLong(4, bb);
                ps.setString(5, b5);
                ps.setString(6, a);

                int check = ps.executeUpdate();

                JOptionPane.showMessageDialog(rootPane, "Sửa thành công hồ sơ!");

            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }     
    }//GEN-LAST:event_btnSửaActionPerformed

    private void btnRutlaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutlaiActionPerformed
        // TODO add your handling code here:
        String u = txtNhap.getText();
        String k = txtmtk.getText();
        if (k.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sổ tiết kiệm cần rút!!!");
        } else {

            String h = txtLai.getText();
            if (h.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập số tiền cần rút!!!");
            } else {

                double tien1 = Double.parseDouble(h);

                int ma1 = Integer.parseInt(k);

                DB_stk sotk = new DB_stk();

                for (Sotietkiem i : sotk.laystk()) {

                    if (i.getMaSTK() == ma1) {

                        if (i.getSotienlai() < tien1) {

                            JOptionPane.showMessageDialog(rootPane, "Số dư trong tiền lãi không đủ!!!");

                        } else {

                            double d1 = i.getSotienlai() - tien1;

                            try {
                                Connection cn = ConectDB.getConectDB();
                                PreparedStatement ps = cn.prepareStatement("update Sotietkiem set Sotienlai=? where Msstk=?");

                                ps.setDouble(1, d1);
                                ps.setInt(2, ma1);

                                int check = ps.executeUpdate();

                                Date date = new java.util.Date();
                                SimpleDateFormat sd = new SimpleDateFormat("hh:mm:ss dd-MM-yyyy");
                                String d = sd.format(date);
                                tien1=tien1/1000000;
                                String nd1 = "Rút "+tien1+" triệu VNĐ tiền lãi từ sổ "+ma1;
                                
                                PreparedStatement ps1 = cn.prepareStatement("Insert into Lichsu (Time, Nhanvien, Noidung, Chuhoso) Values (?,?,?,?)");

                                ps1.setString(1, d);
                                ps1.setString(2, taikhoannhanvien.nhanvien);
                                ps1.setString(3, nd1);
                                ps1.setString(4, u);
                                
                                int check1 = ps1.executeUpdate();

                                JOptionPane.showMessageDialog(rootPane, "Đã rút thành công!");

                            } catch (SQLException ex) {
                                java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRutlaiActionPerformed

    private void btnRutgocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutgocActionPerformed
        // TODO add your handling code here:
        String y = txtNhap.getText();
        String k = txtmtk.getText();
        if (k.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sổ tiết kiệm cần rút!!!");
        } else {

            String h = txtGoc.getText();
            if (h.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập số tiền cần rút!!!");
            } else {

                double tien2 = Double.parseDouble(h);

                int ma2 = Integer.parseInt(k);

                DB_stk sotk = new DB_stk();

                for (Sotietkiem i : sotk.laystk()) {

                    if (i.getMaSTK() == ma2) {

                        if (i.getSotiengoc() < tien2) {

                            JOptionPane.showMessageDialog(rootPane, "Số dư trong tiền gốc không đủ!!!");

                        } else {

                            double d2 = i.getSotiengoc() - tien2;

                            try {
                                Connection cn = ConectDB.getConectDB();
                                PreparedStatement ps = cn.prepareStatement("update Sotietkiem set Sotiengoc=? where Msstk=?");

                                ps.setDouble(1, d2);
                                ps.setInt(2, ma2);

                                int check = ps.executeUpdate();
                                
                                Date date = new java.util.Date();
                                SimpleDateFormat sd = new SimpleDateFormat("hh:mm:ss dd-MM-yyyy");
                                String d = sd.format(date);
                                tien2=tien2/1000000;
                                String nd2 = "Rút "+tien2+" triệu VNĐ tiền gốc từ sổ "+ma2;
                                
                                PreparedStatement ps1 = cn.prepareStatement("Insert into Lichsu (Time, Nhanvien, Noidung, Chuhoso) Values (?,?,?,?)");

                                ps1.setString(1, d);
                                ps1.setString(2, taikhoannhanvien.nhanvien);
                                ps1.setString(3, nd2);
                                ps1.setString(4, y);
                                
                                int check1 = ps1.executeUpdate();


                                JOptionPane.showMessageDialog(rootPane, "Đã rút thành công!");

                            } catch (SQLException ex) {
                                java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRutgocActionPerformed

    private void btnLichsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichsuActionPerformed
        // TODO add your handling code here:
        String a = txtNhap.getText();

        if (a.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập mã hồ sơ!!!");
        } else {

            hosokhachhang.mahoso = a;
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new frmLichsu().setVisible(true);
                }
            });

            setVisible(false);
            dispose();
        }

    }//GEN-LAST:event_btnLichsuActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHoso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLichsu;
    private javax.swing.JButton btnRutgoc;
    private javax.swing.JButton btnRutlai;
    private javax.swing.JButton btnSửa;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnTra;
    private javax.swing.JTextField httt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField ls;
    private javax.swing.JTextField mls;
    private com.toedter.calendar.JDateChooser nt;
    private com.toedter.calendar.JDateChooser nv;
    private javax.swing.JTextField sTv;
    private javax.swing.JTextField sng;
    private javax.swing.JTextField stg;
    private javax.swing.JTextField stl;
    private javax.swing.JTextField stv;
    private javax.swing.JTextField txtGoc;
    private javax.swing.JTextField txtLai;
    private javax.swing.JTextField txtNhap;
    private javax.swing.JTextField txtTra;
    private javax.swing.JTextField txtVay;
    private javax.swing.JTextField txtmtk;
    // End of variables declaration//GEN-END:variables
}
